pod 'ReactiveCocoa'
pod 'Toast'
pod 'WCAlertView'
pod 'SDWebImage'
#pod 'Reveal-iOS-SDK'
pod 'TMCache'
pod 'INTULocationManager'
pod 'VZInspector',:configurations => ['Debug']
pod 'UMengAnalytics-NO-IDFA'
pod 'Pingpp/Alipay', '~> 2.0.5'
pod 'Pingpp/Wx', '~> 2.0.5'
pod 'SECoreTextView'
